# Desafio funcionarios

print('\t ----Total Funcionarios----')
func_total  = set({'Everson', 'Alonso', 'Vargas', 'Jair', 'Keno', 'Rever', 'Mariano', 'Savarino'})
print('\t', func_total)
print('\t Total: ', func_total.__len__())
print()
print('\t ---- Funcionarios que trabalham de dia----')
func_dia = set({'Everson', 'Savarino', 'Keno', 'Jair'})
print('\t', func_dia)
print('\t Total: ', func_dia.__len__())
print()
print('\t ----Funcionarios que trabalham de noite----')
func_noite = set({'Alonso', 'Vargas', 'Rever'})
print('\t', func_noite)
print('\t Total: ', func_noite.__len__())
print()
print('\t ----Funcionarios que tem carro----')
func_carro = set({'Mariano', 'Rever', 'Vargas', 'Jair'})
print('\t', func_carro)
print('\t Total: ', func_carro.__len__())
print()
print('\t ----Funcionarios que trabalham a noite e tem carro----')
func_carro_noite = func_noite.intersection(func_carro)
print('\t', func_carro_noite)
print('\t Total: ', func_carro_noite.__len__())
print()
print('\t ----Funcionarios que trabalham de dia e tem carro----')
func_carro_dia = func_dia.intersection(func_carro)
print('\t', func_carro_dia)
print('\t Total: ', func_carro_dia.__len__())
print()
print('\t ----Funcionarios que não tem carro----')
func_s_carro = func_total.difference(func_carro)
print('\t', func_s_carro)
print('\t Total: ', func_s_carro.__len__())



